### PR TITLE
Add parameter to force copy of modules

### PR DESCRIPTION
**Pull request by pelmato**
This is equivalent to "play dependencies --forceCopy".

### CODE REVIEW

**Comment by gslowikowski** [comment]
Hi. In what context you need this?

**Comment by pelmato** [comment]
Hi, I'm not sure any longer because I wrote it a few months ago.
I think it was because my play application references files (".js" and ".less") in a depending play module using relative paths. If the play module is a file itself, the paths get wrong and my js compilation fails.

**Comment by gslowikowski** [comment]
I've improved the logic a little bit.

New `1.0.0-beta8-SNAPSHOT` snapshot deployed.

Site updated, new parameter is [here](https://play1-maven-plugin.github.io/play1-maven-plugin/1.0.0-beta8-SNAPSHOT/play-maven-plugin/dependencies-mojo.html#dependenciesForceCopy).
Maybe its description should be more precise. It is related to reactor modules only.

Can you check it?

**Comment by pelmato** [comment]
Hi, it seems to work well here. Thank you very much.

**Comment by pelmato** [comment]
I only have one more question: when do you plan to release next version? Maven central indicates that last version is 1.0.0-beta7, which was released 2 years ago. I will use a local repository for now, but it would be nice to use a public release.

**Comment by gslowikowski** [comment]
I hope very soon. Need to test it and look at the documentation because it was converted from wiki pages in a hurry when moving from GoogleCode to GitHub.

**Pull request merged**
